CREATE TABLE covid_deaths(
	iso_code text,
	continent text, 
	location text,
	date date,
	population float, 
	total_cases float, 
	new_cases int, 
	new_cases_smoothed float, 
	total_deaths float, 
	new_deaths int, 
	new_deaths_smoothed float, 
	total_cases_per_million float, 
	new_cases_per_million float, 
	new_cases_smoothed_per_million float, 
	total_deaths_per_million float, 
	new_deaths_per_million float, 
	new_deaths_smoothed_per_million float, 
	reproduction_rate float, 
	icu_patients int, 
	icu_patients_per_million float, 
	hosp_patients int, 
	hosp_patients_per_million float, 
	weekly_icu_admissions int, 
	weekly_icu_admissions_per_million float, 
	weekly_hosp_admissions int, 
	weekly_hosp_admissions_per_million float
)